// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL7YGZagjCchjjl_ve5JjigNw1ATC1KWM',
    appId: '1:681823732563:web:bb2e848c92d3ff37e457a6',
    messagingSenderId: '681823732563',
    projectId: 'virtualfridge-9fa74',
    authDomain: 'virtualfridge-9fa74.firebaseapp.com',
    storageBucket: 'virtualfridge-9fa74.firebasestorage.app',
    measurementId: 'G-9ST2BS3SVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoW2CfqCzzKz4yD9oxB48uZP_2vsZShhM',
    appId: '1:681823732563:android:cc82344a3f4251dee457a6',
    messagingSenderId: '681823732563',
    projectId: 'virtualfridge-9fa74',
    storageBucket: 'virtualfridge-9fa74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0NKLSpCuZVikklaqX9Kq2E1w32Xgll6c',
    appId: '1:681823732563:ios:0660d8a586bf3070e457a6',
    messagingSenderId: '681823732563',
    projectId: 'virtualfridge-9fa74',
    storageBucket: 'virtualfridge-9fa74.firebasestorage.app',
    iosBundleId: 'com.example.virtualfridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0NKLSpCuZVikklaqX9Kq2E1w32Xgll6c',
    appId: '1:681823732563:ios:0660d8a586bf3070e457a6',
    messagingSenderId: '681823732563',
    projectId: 'virtualfridge-9fa74',
    storageBucket: 'virtualfridge-9fa74.firebasestorage.app',
    iosBundleId: 'com.example.virtualfridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL7YGZagjCchjjl_ve5JjigNw1ATC1KWM',
    appId: '1:681823732563:web:a72110d17da1f3d0e457a6',
    messagingSenderId: '681823732563',
    projectId: 'virtualfridge-9fa74',
    authDomain: 'virtualfridge-9fa74.firebaseapp.com',
    storageBucket: 'virtualfridge-9fa74.firebasestorage.app',
    measurementId: 'G-KS2WEV9XV0',
  );
}
